Repository nightven/ninja-sushi, pull requests merged in 2024-03, with the labels that each got.

#2 create category-component
  src/app/home/page.tsx
  src/app/page.tsx
  src/assets/arow-down.svg
  src/assets/bell.svg
  src/assets/cost.svg
  src/assets/favorite.svg
  src/assets/phone.svg
  src/assets/profile.svg
  src/assets/sprite.svg
  src/assets/svgs/bowl.svg
  src/assets/svgs/drink.svg
  src/assets/svgs/sauce.svg
  src/assets/svgs/set.svg
  src/assets/svgs/sushi.svg
  src/assets/svgs/unknown.svg
  src/assets/ua.svg
  src/components/Category/Category.tsx
Labels: enhancement

#4 Ss 13 backend setting
  .env
  package-lock.json
  package.json
  src/app/api/ingredients/route.ts
  src/app/api/news/route.ts
  src/app/api/products/route.ts
  src/app/api/users/route.ts
  src/lib/auth/auth.config.ts
  src/lib/auth/auth.ts
  src/lib/db/connect.ts
  src/lib/db/public/regex.ts
  src/lib/models/ingredients.ts
  src/lib/models/news.ts
  src/lib/models/products.ts
  src/lib/models/users.ts
  src/lib/routes/ingredients.ts
  src/lib/routes/news.ts
  src/lib/routes/products.ts
  src/lib/routes/users.ts
  src/middleware.ts
Labels: documentation, enhancement

#6 Ss 12 hero component
  package-lock.json
  package.json
  src/app/page.tsx
  src/assets/images/hero1.png
  src/assets/images/hero2.jpg
  src/assets/images/hero3.jpg
  src/assets/images/hero4.jpg
  src/assets/svgs/category/bowl.svg
  src/assets/svgs/category/drink.svg
  src/assets/svgs/category/roll.svg
  src/assets/svgs/category/sauce.svg
  src/assets/svgs/category/set.svg
  src/assets/svgs/category/sushi.svg
  src/assets/svgs/category/unknown.svg
  src/components/Category/Category.tsx
  src/components/Description/Description.tsx
  src/components/Slider/Slider.tsx
  utils/constants.ts
Labels: enhancement

#10 Ss 15 adaptive hero
  src/app/page.tsx
  src/components/Category/Category.tsx
  src/components/Products/Products.tsx
Labels: wontfix

#12 products render
  src/components/Products/Products.tsx
Labels: enhancement

#15 Ss 17 news page
  public/new1.png
  public/new2.png
  src/app/news/[slug]/page.tsx
  src/app/news/page.tsx
  src/assets/svgs/news/home.svg
  src/assets/svgs/news/search.svg
  src/components/News/News.tsx
Labels: enhancement

#17 no filters
  src/app/api/ingredients/route.ts
  src/app/api/products/route.ts
  src/lib/models/ingredients.ts
  src/lib/routes/ingredients.ts
  src/lib/routes/products.ts
Labels: enhancement

#19 routes news
  src/app/api/news/[slug]/route.ts
  src/lib/models/news.ts
  src/lib/routes/news.ts
Labels: enhancement

#20 add cost
  src/app/globals.css
  src/app/page.tsx
  src/components/Header/BurgerMenu.tsx
  src/components/Header/Cost.tsx
  src/components/Header/Header.tsx
  src/components/Header/NavListItem.tsx
  src/components/Header/ToolsBar.tsx
  src/components/Header/ToolsBarItem.tsx
  src/components/header/navList.tsx
  src/constans/navigations.ts
  src/hooks/useOutsideClick.ts
Labels: enhancement

#21 render with an API newsPage, oneNew + styles
  src/app/news/[slug]/page.tsx
  src/app/news/page.tsx
  src/assets/svgs/news/home.svg
  src/assets/svgs/news/search.svg
  src/components/News/News.tsx
  src/components/News/NewsList.tsx
Labels: enhancement

#16 Ss 18 products component
  src/app/globals.css
  src/app/page.tsx
  src/assets/svgs/products/Heart.svg
  src/assets/svgs/products/Lactose.svg
  src/assets/svgs/products/Plus.svg
  src/assets/svgs/products/Spicy.svg
  src/assets/svgs/products/Vegan.svg
  src/components/Category/Category.tsx
  src/components/Description/Description.tsx
  src/components/ProductList/ClientSideProduct.tsx
  src/components/ProductList/ProductGroup.tsx
  src/components/ProductList/ProductItem.tsx
  src/components/ProductList/ProductList.tsx
  src/components/Products/Products.tsx
  src/components/Slider/Slider.tsx
  src/lib/routes/products.ts
  src/types/productTypes.ts
Labels: enhancement
